version: 2.1
workflows:
  commit:
    jobs:
      - build-and-push:
          context: autodash-rpi
jobs:
  build-and-push:
    resource_class: mchineboy/auto-dash
    machine: true
    steps:
      - checkout
      - run: |
          uname -a
          pwd
          ls
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_LOGIN --password-stdin 
          docker build -t mchineboy007/auto-dash:latest .
          docker push mchineboy007/auto-dash:latest
          docker system prune -f
          docker create --rm --device=/dev/mem --device=/dev/gpiomem --device=/dev/spidev0.0 --device=/dev/spidev0.1 --pull always mchineboy007/auto-dash:latest 
