version: 2.1
orbs:
  docker: circleci/docker@2.0.2
workflows:
  commit:
    build-workflow:
      - build-and-push:
          context: autodash-rpi
jobs:
  build-and-push:
    executor: docker/docker
    resource_class: mchineboy/auto-dash
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: mchineboy007/auto-dash
      - docker/push:
          digest-path: /tmp/digest.txt
          image: mchineboy007/auto-dash
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"
