version: 2.1
orbs:
  docker: circleci/docker@2.0.2
workflows:
  build:
    jobs:
      - build:
          context: autodash-rpi
jobs:
  build:
    executor: docker/docker
    steps:
      - docker/publish:
        image: mchineboy007/auto-dash:latest
        update-description: true
