version: 2.1
orbs:
  docker: circleci/docker@2.0.2
workflows:
  build:
    jobs:
      - build:
          context: autodash-rpi
jobs:
  build:
    executor: docker/docker
    docker:
      - image: cimg/go:1.17.8
    resource_class: mchineboy/auto-dash
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
        image: mchineboy/auto-dash
      - docker/push:
        digest-path: /tmp/digest.txt
        image: mchineboy/auto-dash
      - run:
        command: |
          echo "Digest is $(</tmp/digest.txt)"
