version: 2.1
workflows:
  testing:
    jobs:
      - build:
        context:
          - "autodash-rpi"
jobs:
  build:
    docker: circleci/go:latest
    resource_class: mchineboy/auto-dash
    steps:
      - checkout
      - run:
          name: "build docker image"
          command: |
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_LOGIN --password-stdin 
            docker build . -t mchineboy/auto-dash:latest 
            docker push mchineboy007/auto-dash:latest
