version: 2.1
orbs:
  docker: circleci/docker@2.0.2
workflows:
  commit:
    jobs:
      - build-and-push:
          context: autodash-rpi
jobs:
  build-and-push:
    resource_class: mchineboy/auto-dash
    machine: true
    steps:
      - checkout
      - run: |
          sudo apt update
          sudo apt -y install docker
          uname -a
          export PATH=/snap/bin:$PATH
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_LOGIN --password-stdin 
          docker build -t mchineboy007/auto-dash:latest 
          docker push mchineboy007/auto-dash:latest
